name: ev
description: " "
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.0 # Updated package_info_plus version to ^2.1.0
  cupertino_icons: ^1.0.2 # Updated cupertino_icons version to ^1.0.2
  web_socket_channel: ^3.0.0
  http: ^1.2.1  # Updated http package to ^0.14.0
  crypto: ^3.0.3
  fluttertoast: ^8.0.8 # Updated fluttertoast version to ^8.0.8
  shared_preferences: ^2.0.6 # Updated shared_preferences version to ^2.0.6
  provider: ^6.1.2 # Updated provider version to ^5.0.0
  razorpay_flutter: ^1.3.6
  flutter_dialogs: ^3.0.0
  intl: ^0.19.0 # Updated intl version to ^0.17.0
  qr_code_scanner: ^1.0.1



dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Image/